version: "3.9"
services:
  traefik:
    restart: unless-stopped
    image: traefik:v2.6
    container_name: traefik
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - target: 80
        published: 5000
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dynamic_conf.yml:/config/dynamic_conf.yml:ro
      - ./certificates:/certificates:ro
      - ./traefik.yml:/traefik.yml:ro
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.http.routers.traefik.entrypoints=http
        - traefik.http.middlewares.admin-auth.basicauth.users=admin:admin # ${USERNAME?Variable not set}:${HASHED_PASSWORD?Variable not set}
        - traefik.http.routers.traefik.rule=Host(`traefik.spinner.test`)
        - traefik.http.middlewares.traefik-auth.basicauth.users=admin:admin
        - traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        - traefik.http.routers.traefik.middlewares=traefik-https-redirect
        - traefik.http.routers.traefik-secure.entrypoints=https
        - traefik.http.routers.traefik-secure.rule=Host(`traefik.spinner.test`)
        - traefik.http.routers.traefik-secure.middlewares=traefik-auth
        - traefik.http.routers.traefik-secure.tls=true
        - traefik.http.routers.traefik-secure.tls.certresolver=http
        - traefik.http.routers.traefik-secure.service=api@internal
        - traefik.http.services.traefik.loadbalancer.server.port=8080
    command:
      - --providers.docker
      - --providers.docker.swarmmode
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --certificatesresolvers.le.acme.email=admin@example.com # ${EMAIL?Variable not set}
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --accesslog
      - --log
      - --api
networks:
  proxy:
    external: true
